channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.0
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.1
  - scipy==1.13.0
name: mlflow-env